### ISSUE TITLE
队伍伤害显示接口错误

### ISSUE THREAD

**Issue by ayakasuki** [AFanSKyQs/FanSky_Qs#59]
```
0|Miao-Yun | [MiaoYz][17:23:27.260][INFO] SyntaxError: Unexpected end of JSON input
0|Miao-Yun |     at JSON.parse (<anonymous>)
0|Miao-Yun |     at Response.json (file:///data1/Yunzai-Bot/Miao-Yunzai/node_modules/.pnpm/node-fetch@3.3.1/node_modules/node-fetch/src/body.js:149:15)
0|Miao-Yun |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Miao-Yun |     at async getTeyvatData (file:///data1/Yunzai-Bot/Miao-Yunzai/plugins/FanSky_Qs/apps/Teyvat/getTeam.js:379:30)
0|Miao-Yun |     at async team (file:///data1/Yunzai-Bot/Miao-Yunzai/plugins/FanSky_Qs/apps/Teyvat/getTeam.js:127:23)
0|Miao-Yun |     at async BotEntry.RequestSelect (file:///data1/Yunzai-Bot/Miao-Yunzai/plugins/FanSky_Qs/apps/Teyvat/BotEntry.js:231:13)
0|Miao-Yun |     at async BotEntry.TeyvatEnTry (file:///data1/Yunzai-Bot/Miao-Yunzai/plugins/FanSky_Qs/apps/Teyvat/BotEntry.js:223:9)
0|Miao-Yun |     at async PluginsLoader.deal (file:///data1/Yunzai-Bot/Miao-Yunzai/lib/plugins/loader.js:269:54)
0|Miao-Yun | [MiaoYz][17:23:27.262][ERRO] >>>[错误信息] 提瓦特小助手接口无法访问或返回错误
```

**Comment by AFanSKyQs** [comment]
这个可能是某些角色数据有问题或者不支持伤害计算，或者是接口单纯地歇了，等待恢复即可~
